version: '3'
services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerFile/Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - ./:/app
     - /app/node_modules
    restart: always
    environment:
      - MONGO_URL=mongodb://root:root@mongo/ionEnergy?authSource=admin
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4
    command: [--auth]
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/db:/data/db
    ports:
      - "27018:27017"
    restart: always